Set Space choices dynamically
The `DefaultLocationField` and its `DefaultLocationWidget` query the
`Space` model when the `DefaultLocationsForm` is imported which
produces this error because the necessary tables are not created yet:

```
django.db.utils.ProgrammingError: (1146, "Table 'SS.locations_space' doesn't exist")
```

This sets the choices for the fields and widgets dynamically from the
`DefaultLocationsForm` initialization instead.